import React from 'react';
import Head from 'next/head'
const HeadTag = () => {
    return (
        <Head>
            <title>Abdalrahman Mohamed Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default HeadTag;
